input {
  # Mở cổng TCP 5044 đón log định dạng JSON
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  # Nơi thêm các bộ lọc dữ liệu nếu cần
}

output {
  # 1. Đẩy 1 bản vào Kafka cho AI đọc
  kafka {
    bootstrap_servers => "kafka:9092"
    topic_id => "snort-logs"
    codec => json
  }

  # 2. Đẩy 1 bản vào Elasticsearch để lưu trữ và vẽ Dashboard
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "snort-alerts-%{+YYYY.MM.dd}"
  }
  
  # In ra màn hình console của Logstash để dễ debug
  stdout { codec => rubydebug }
}